JEDI_act pushBack (player addAction["<t color='#0099FF'>Sit Down</t>",{
	removeAllWeapons player;
	removeAllItems player;
	removeAllAssignedItems player;
	removeUniform player;
	removeVest player;
	removeBackpack player;
	removeHeadgear player;
	removeGoggles player;

player forceAddUniform 'everestwlandClothing';
for '_i' from 1 to 10 do {player addItemToUniform 'ACE_fieldDressing';};
for '_i' from 1 to 5 do {player addItemToUniform 'ACE_morphine';};
for '_i' from 1 to 5 do {player addItemToUniform 'ACE_epinephrine';};
for '_i' from 1 to 2 do {player addItemToUniform '16Rnd_9x21_Mag';};
player addItemToUniform 'rhs_mag_30Rnd_556x45_Mk318_Stanag';
player addItemToUniform 'HandGrenade';
player addVest 'wlandVest';
player addItemToVest '16Rnd_9x21_Mag';
for '_i' from 1 to 2 do {player addItemToVest 'HandGrenade';};
for '_i' from 1 to 5 do {player addItemToVest 'rhs_mag_30Rnd_556x45_Mk318_Stanag';};
for '_i' from 1 to 4 do {player addItemToVest 'rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Orange';};
for '_i' from 1 to 2 do {player addItemToVest 'ACE_M84';};
player addBackpack 'everest_packWland';
player addItemToBackpack 'ToolKit';
player addItemToBackpack 'ACE_EarPlugs';
player addItemToBackpack 'ACE_Flashlight_XL50';
player addItemToBackpack 'HandGrenade';
player addItemToBackpack 'SmokeShellRed';
player addItemToBackpack 'SmokeShellGreen';
for '_i' from 1 to 5 do {player addItemToBackpack 'Chemlight_green';};
for '_i' from 1 to 5 do {player addItemToBackpack 'Chemlight_red';};
for '_i' from 1 to 3 do {player addItemToBackpack 'B_IR_Grenade';};
for '_i' from 1 to 10 do {player addItemToBackpack 'SmokeShell';};
player addHeadgear 'wland_ECH';
player addGoggles 'G_mas_wpn_shemag';

comment 'Add weapons';
player addWeapon 'rhs_weap_m4a1';
player addPrimaryWeaponItem 'rhsusf_acc_nt4_black';
player addPrimaryWeaponItem 'rhsusf_acc_anpeq15side_bk';
player addPrimaryWeaponItem 'ACE_optic_Hamr_PIP';
player addWeapon 'hgun_Rook40_F';
player addWeapon 'ACE_VectorDay';

player linkItem 'ItemCompass';
player linkItem 'ItemMap';
player linkItem 'ACE_Altimeter';
player linkItem 'tf_anprc152_2';
player linkItem 'ItemGPS';
player linkItem 'NVGoggles_OPFOR';
},true,1,true,true,"""",'player distance cursorTarget < 6 && {([str cursorTarget,"B_officer_F"] call KRON_StrInStr)} ']);